version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=tickets
      - POSTGRES_USER=tickets
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always