"""empty message

Revision ID: 10379dc4c6ff
Revises: 41607af54856
Create Date: 2021-11-13 11:28:32.096307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10379dc4c6ff'
down_revision = '41607af54856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
