"""empty message

Revision ID: 3d775c35f14d
Revises: 5fc004858a1c
Create Date: 2021-11-13 11:41:13.572268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d775c35f14d'
down_revision = '5fc004858a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_type', sa.Enum('admin', 'user', name='accounttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_type')
    # ### end Alembic commands ###
