"""empty message

Revision ID: 41607af54856
Revises: 
Create Date: 2021-11-11 19:42:46.372066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41607af54856'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(), nullable=True),
    sa.Column('longitude', sa.DECIMAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('account_type', sa.Enum('Administrator', 'User', name='accounttype'), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('station_type', sa.Enum('airport', 'railway_station', name='stationtypeenum'), nullable=True),
    sa.Column('id_locality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_locality'], ['locality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id_station_departure', sa.Integer(), nullable=True),
    sa.Column('id_station_arrival', sa.Integer(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.Column('passenger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_station_arrival'], ['station.id'], ),
    sa.ForeignKeyConstraint(['id_station_departure'], ['station.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('station')
    op.drop_table('user')
    op.drop_table('locality')
    # ### end Alembic commands ###
