"""empty message

Revision ID: 5fc004858a1c
Revises: 10379dc4c6ff
Create Date: 2021-11-13 11:40:57.698535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc004858a1c'
down_revision = '10379dc4c6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_type', sa.VARCHAR(length=13), nullable=True))
    # ### end Alembic commands ###
