"""empty message

Revision ID: cf638e9e0dfb
Revises: 18d5989fdd1b
Create Date: 2021-11-20 17:22:24.570261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf638e9e0dfb'
down_revision = '18d5989fdd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('departure_time', sa.DateTime(), nullable=True),
    sa.Column('arrival_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_to_station',
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], )
    )
    op.add_column('ticket', sa.Column('flight_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ticket', 'flight', ['flight_id'], ['id'])
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('user', 'name')
    op.drop_column('user', 'account_type')
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('account_type', sa.VARCHAR(length=5), nullable=True))
    op.add_column('user', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'full_name')
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_column('ticket', 'flight_id')
    op.drop_table('flight_to_station')
    op.drop_table('flight')
    # ### end Alembic commands ###
